from turtle import title
import praw
import requests
import urllib.request
import os, shutil
import webbrowser
import keyboard
import time


folder = './downloads'
for filename in os.listdir(folder):
    file_path = os.path.join(folder, filename)
    try:
        if os.path.isfile(file_path) or os.path.islink(file_path):
            os.unlink(file_path)
        elif os.path.isdir(file_path):
            shutil.rmtree(file_path)
    except Exception as e:
        print('Failed to delete %s. Reason: %s' % (file_path, e))

twitch_credentials = {
    'Authorization': 'Bearer lpgq7xeeicac21yqakub3ddd6fbp9c',
    'Client-Id': 'pojq491dhden9c7x27bygt7l4mtvhm'
    }

reddit = praw.Reddit(
    client_id= "d2lbkhguijzKYLTov-nP1A",
    client_secret= "L4qbLtoulnURFPFD8n7FyT8nmFJ7Lw",
    user_agent= "scraper-xsvl",
)


subreddit = reddit.subreddit("LivestreamFail")



for submission in subreddit.top(time_filter='day', limit=6):
    if "https://clips.twitch.tv/" in submission.url:
        #print("/////////////////////////")
        print(submission.title)
        print(submission.url)
        #print("/////////////////////////")
        output = submission.url.replace("https://clips.twitch.tv/", "https://api.twitch.tv/helix/clips?id=")
        #print(output)
        r = requests.get(output, headers= twitch_credentials).json()
        print(r)
        try:
            ar = r["data"][0]["thumbnail_url"]
            ar = ar.replace("-preview-480x272.jpg", ".mp4")
            print(ar)
            urllib.request.urlretrieve(ar, 'downloads/' + submission.title.replace("sex", "seggs", 1) + '.mp4')
            
            
            
        except IndexError:
            pass



webbrowser.open('https://www.tiktok.com/upload?lang=nl-NL')

def upload():
    time.sleep(4)
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("enter")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("enter")
    keyboard.write("E:\Git-desktop\Reddit-Scraper\downloads")
    keyboard.press_and_release("enter")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("right arrow")
    keyboard.press_and_release("left arrow")
    time.sleep(0.5)
    keyboard.press_and_release("enter")
    time.sleep(20)
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("ctrl+down arrow")
    time.sleep(0.5)
    keyboard.press_and_release("space")
    keyboard.write("#fyp #viral #twitch #clips #funny")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("enter")

    time.sleep(0.5)
    webbrowser.open('https://www.tiktok.com/upload?lang=nl-NL')
    time.sleep(4)
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("enter")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("enter")
    keyboard.write("E:\Git-desktop\Reddit-Scraper\downloads")
    keyboard.press_and_release("enter")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("right arrow")
    keyboard.press_and_release("left arrow")
    keyboard.press_and_release("right arrow")
    time.sleep(0.5)
    keyboard.press_and_release("enter")
    time.sleep(20)
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("ctrl+down arrow")
    time.sleep(0.5)
    keyboard.press_and_release("space")
    keyboard.write("#fyp #viral #twitch #clips #funny")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("enter")

    time.sleep(0.5)
    webbrowser.open('https://www.tiktok.com/upload?lang=nl-NL')
    time.sleep(4)
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("enter")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("enter")
    keyboard.write("E:\Git-desktop\Reddit-Scraper\downloads")
    keyboard.press_and_release("enter")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("right arrow")
    keyboard.press_and_release("left arrow")
    keyboard.press_and_release("right arrow")
    keyboard.press_and_release("right arrow")
    time.sleep(0.5)
    keyboard.press_and_release("enter")
    time.sleep(20)
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("ctrl+down arrow")
    time.sleep(0.5)
    keyboard.press_and_release("space")
    keyboard.write("#fyp #viral #twitch #clips #funny")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("enter")

    time.sleep(0.5)
    webbrowser.open('https://www.tiktok.com/upload?lang=nl-NL')
    time.sleep(4)
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("enter")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("enter")
    keyboard.write("E:\Git-desktop\Reddit-Scraper\downloads")
    keyboard.press_and_release("enter")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("tab")
    time.sleep(1)
    keyboard.press_and_release("right arrow")
    keyboard.press_and_release("left arrow")
    keyboard.press_and_release("right arrow")
    keyboard.press_and_release("right arrow")
    keyboard.press_and_release("right arrow")
    time.sleep(0.5)
    keyboard.press_and_release("enter")
    time.sleep(20)
    keyboard.press_and_release("tab")
    keyboard.press_and_release("tab")
    keyboard.press_and_release("ctrl+down arrow")
    time.sleep(0.5)
    keyboard.press_and_release("space")
    keyboard.write("#fyp #viral #twitch #clips #funny")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("tab")
    time.sleep(0.5)
    keyboard.press_and_release("enter")


    time.sleep(5)
    keyboard.press_and_release("ctrl+w")
    time.sleep(0.5)
    keyboard.press_and_release("ctrl+w")
    time.sleep(0.5)
    keyboard.press_and_release("ctrl+w")
    time.sleep(0.5)
    keyboard.press_and_release("ctrl+w")






upload()
